baseurl = "http://busi-base.tk/"
languageCode = "ja"
title = "Busi-base"

theme = "hugo-xmag"
canonifyurls = true
googleAnalytics = "UA-107250739-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 6

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4


[params]
    description = "就活・営業に使える情報を発信"

    summary_length = 300
    github_edit = ""
    footer = "&copy; kumamon 2017 |  [Twitter Follow me!](https://twitter.com/innovative_usjp)"

[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
